# Libraries in General and Numpy in Particular

## 1. Importing Python Libraries

Part of the reason why Python is such a powerful tool for data science is that other people have written and optimized functions and wrapped them into **libraries** that we can bring into our own work.

![numpy](https://raw.githubusercontent.com/donnemartin/data-science-ipython-notebooks/master/images/numpy.png)

[NumPy](https://www.numpy.org/) is the fundamental package for scientific computing with Python. 


To use a package in your current workspace type `import` followed by the name of the library as shown below.

In [1]:
import numpy

That worked because numpy is [included with Anaconda](https://docs.anaconda.com/anaconda/packages/py3.7_osx-64/), so numpy was installed when you installed Anaconda. Other packages will need to be installed before you can use them.

Let's try importing azure (which is a library for using MS Azure in Python).

In [2]:
#import azure

ModuleNotFoundError: No module named 'azure'

That failed because azure is **not** included with Anaconda. In order to get this package, we'll have to install it first:

In [3]:
# I'll install this using PIP, the package installer for Python.
# This is a bash command, but I can run this in the notebook by
# prefixing the command with a '!' ("bang"):

!pip install azure

     |████████████████████████████████| 317kB 3.5MB/s eta 0:00:01
     |████████████████████████████████| 61kB 15.7MB/s eta 0:00:01
     |████████████████████████████████| 81kB 8.7MB/s eta 0:00:011
     |████████████████████████████████| 174kB 8.3MB/s eta 0:00:01
     |████████████████████████████████| 71kB 12.9MB/s eta 0:00:01
     |████████████████████████████████| 358kB 6.5MB/s eta 0:00:01
     |████████████████████████████████| 81kB 22.7MB/s eta 0:00:01
     |████████████████████████████████| 133kB 6.7MB/s eta 0:00:01
     |████████████████████████████████| 1.1MB 9.6MB/s eta 0:00:01
     |████████████████████████████████| 112kB 11.2MB/s eta 0:00:01
     |████████████████████████████████| 40kB 18.8MB/s eta 0:00:01
     |████████████████████████████████| 51kB 19.4MB/s eta 0:00:01
     |████████████████████████████████| 61kB 19.6MB/s eta 0:00:01
     |████████████████████████████████| 92kB 15.8MB/s eta 0:00:01
     |████████████████████████████████| 61kB 25.7MB/s eta 0:00:01
     |███

     |████████████████████████████████| 112kB 2.7MB/s eta 0:00:01
     |████████████████████████████████| 184kB 16.7MB/s eta 0:00:01
     |████████████████████████████████| 51kB 17.9MB/s eta 0:00:01
     |████████████████████████████████| 51kB 11.5MB/s eta 0:00:01
     |████████████████████████████████| 788kB 11.4MB/s eta 0:00:01
     |████████████████████████████████| 51kB 27.7MB/s eta 0:00:01
     |████████████████████████████████| 122kB 12.8MB/s eta 0:00:01
     |████████████████████████████████| 194kB 8.1MB/s eta 0:00:01
     |████████████████████████████████| 51kB 24.1MB/s eta 0:00:01
     |████████████████████████████████| 51kB 17.1MB/s eta 0:00:01
     |████████████████████████████████| 256kB 13.5MB/s eta 0:00:01
     |████████████████████████████████| 102kB 12.0MB/s ta 0:00:01
     |████████████████████████████████| 3.0MB 11.3MB/s eta 0:00:01
     |████████████████████████████████| 81kB 9.8MB/s  eta 0:00:01
     |████████████████████████████████| 573kB 13.9MB/s eta 0:00:01
    

     |████████████████████████████████| 92kB 4.2MB/s eta 0:00:011
     |████████████████████████████████| 71kB 20.7MB/s eta 0:00:01
     |████████████████████████████████| 194kB 13.2MB/s eta 0:00:01
     |████████████████████████████████| 81kB 11.4MB/s eta 0:00:01
     |████████████████████████████████| 491kB 13.1MB/s eta 0:00:01
     |████████████████████████████████| 61kB 17.2MB/s eta 0:00:01
     |████████████████████████████████| 727kB 16.2MB/s eta 0:00:01
     |████████████████████████████████| 61kB 18.7MB/s eta 0:00:01
     |████████████████████████████████| 112kB 18.4MB/s eta 0:00:01
     |████████████████████████████████| 307kB 9.1MB/s eta 0:00:01
     |████████████████████████████████| 40kB 14.1MB/s eta 0:00:01
     |████████████████████████████████| 92kB 17.8MB/s eta 0:00:01
     |████████████████████████████████| 61kB 6.9MB/s eta 0:00:011
     |████████████████████████████████| 92kB 19.5MB/s eta 0:00:01
     |████████████████████████████████| 143kB 13.2MB/s eta 0:00:01
     

     |████████████████████████████████| 563kB 11.3MB/s eta 0:00:01
     |████████████████████████████████| 102kB 3.4MB/s ta 0:00:011
     |████████████████████████████████| 419kB 9.3MB/s eta 0:00:01
     |████████████████████████████████| 51kB 9.1MB/s  eta 0:00:01
^C


Now I can import the library:

In [4]:
import azure

Many packages have standard import aliases. We effect this aliasing by using the Python keyword `as`. For numpy, the standard alias is `np`.

In [6]:
import numpy as np

x = np.array([1,2,3])
print(x)
type(x)

[1 2 3]


numpy.ndarray

Of course we could use any alias we like, including Python keywords! But if we did this, we'd overwrite the meaning of those keywords.

## 2. NumPy versus base Python

Now that we know libraries exist, why do we want to use them? Let us examine a comparison between base Python and Numpy.

Python has lists and normal python can do basic math. NumPy, however, has the helpful objects called arrays.

Numpy has a few advantages over base Python which we will look at.

In [7]:
names_list = ['Bob', 'John', 'Sally']

#use numpy.array for numbers and numpy.char.array for strings

names_array = numpy.char.array(['Bob','John','Sally'])

print(names_list)
print(names_array)

['Bob', 'John', 'Sally']
['Bob' 'John' 'Sally']


In [11]:
# Make a list and an array of three numbers

#your code here


In [12]:
# multiply your array by 3


In [13]:
# multiply your list by 3



Numpy arrays support the _div_ operator while python lists do not. There are other things that make it useful to utilize numpy over base python for evaluating data.

Below, you will find a piece of code we will use to compare the speed of operations on a list and operations on an array.

In [14]:
size_of_vec = 1000

X = range(size_of_vec)
Y = range(size_of_vec)

In [15]:
%timeit [X[i] + Y[i] for i in range(len(X))]

198 µs ± 1.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [16]:
X = np.arange(size_of_vec)
Y = np.arange(size_of_vec)

In [17]:
%timeit X + Y

882 ns ± 94.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## 3. What Else Can Numpy Do?

Type `numbers_list.` and then hit `TAB`. What options do you have?

In [21]:
numbers_list.

The names of standard Python list attributes and methods appear:

- `append(x)` (add x to the end of the list)
- `clear()` (delete all elements of the list)
- `copy()` (make a copy of the list)
- `count(x)` (return the number of instances of x in the list)
- `extend([x, y])` (add x and y to the end of the list)
- `index(x)` (return the position in the list of x)
- `insert(x, y)` (insert y into position x in the list)
- `pop(i=-1)` (remove and return the element at position i in the list)
- `remove(x)` (remove x from the list)
- `reverse()` (reverse the order of the elements of the list)
- `sort()` (sort the elements of the list)

Now type `numbers_array.` and then hit `TAB`. What options do you have?

In [24]:
numbers_array.

3

Now there are many new options!

Exercise: Write down quick one-liners to describe what these methods do:


- `max()`
- `mean()`
- `min()`
- `round()`
- `std()`
- `sum()`

### Better Math Tools

#### Trigonometry:
- `np.pi` for $\pi$

In [25]:
np.pi

3.141592653589793

- `np.sin()` for the sine function

In [26]:
np.sin(np.pi / 6)

0.49999999999999994

- `np.cos()` for the cosine function
- `np.tan()` for the tangent function
- `np.sinh()` for the hyperbolic sine function
- `np.cosh()` for the hyperbolic cosine function
- `np.tanh()` for the hyperbolic tangent function

#### Number Theory:
- `np.binary_repr()` to convert from decimal to binary

In [27]:
np.binary_repr(10)

'1010'

- `np.diff()` to calculate, recursively, the differences between sequence terms

In [28]:
np.diff([1, 4, 9, 16])

array([3, 5, 7])

In [29]:
np.diff([1, 4, 9, 16], n=2)

array([2, 2])

- `np.gcd()` for the greatest common divisor

In [30]:
np.gcd(8, 100)

4

#### Array Logic:
- `np.bitwise_not()`
- `np.bitwise_and()`

In [31]:
np.bitwise_and([True, False, True], [False, True, True])

array([False, False,  True])

- `np.bitwise_or()`
- `np.bitwise_xor()`
- `np.concatenate()`

In [32]:
np.concatenate([[1, 2], [3, 4]])

array([1, 2, 3, 4])

#### Complex Numbers:
- `np.complex()`

In [33]:
np.complex(2, -3)

(2-3j)

#### Data Analysis:
- `np.histogram()`

In [34]:
np.histogram([1, 2])

(array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ]))

#### Logarithms:
- `np.exp()` for Euler's number with exponent

In [35]:
np.exp(2)

7.38905609893065

- `np.log()` for logarithms

In [36]:
np.log(10)

2.302585092994046

#### Linear Algebra:

`np.linalg` is an incredibly useful module for matrix mathematics, which we shall need in future lessons!

### More Tools

See [here](https://numpy.org/devdocs/user/basics.html) for more information about numpy. Let's go over some of these points:

#### [More numeric data types than base Python](https://numpy.org/devdocs/user/basics.types.html)

#### Intrinsic array constructors:

In [37]:
print(np.zeros(10))
print(np.ones(10))
print(np.arange(10, dtype=float))
print(np.linspace(0.1, 1, 10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


#### Multi-dimensional indexing:

In [38]:
nums = np.array([[1, 2, 3], [4, 5, 6]])
nums.shape

(2, 3)

In [39]:
nums[0, 2]

3

Why is this more efficient than `nums[0][2]`?

In [40]:
%timeit nums[0, 2]

120 ns ± 2.75 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [41]:
%timeit nums[0][2]

234 ns ± 4.02 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#### Filtering:

In [42]:
data = np.array([10, 3, 4, 7, 6])

In [43]:
data[data < 5]

array([3, 4])

#### Broadcasting:

In [44]:
arr1 = np.array([-1, -2, -3])
arr2 = -8

In [45]:
arr1 + arr2

array([ -9, -10, -11])

Two arrays can be broadcast together if their dimensions have *the same* value or if one of the dimensions has a value of *1*.

In [46]:
arr3 = np.array([[-10., 3., 175.2], [25., 1.47, 9.36]])
arr4 = np.array([5, 5, 5])

In [47]:
arr3 * arr4

array([[-50.  ,  15.  , 876.  ],
       [125.  ,   7.35,  46.8 ]])

#### np.nan and np.inf

NaN stands for "not a number". Numpy's np.nan is a handy way of representing these, in part because np.nan *is a float!*

In [48]:
type(np.nan)

float

This makes it convenient to perform mathematical operations on arrays that contain NaNs.

In [49]:
arr5 = np.array([1, 10, np.nan])

In [50]:
arr5.mean()

nan

Even though the array has a NaN, we don't get an error in calculating its mean. Moreover, we can do this:

In [51]:
np.nansum(arr5) / len(arr5)

3.6666666666666665

And this:

In [52]:
np.nanmean(arr5)

5.5

In [53]:
np.inf

inf

In [54]:
np.isfinite(np.inf)

False

In [55]:
def inv(x):
    return x**(-2)

In [56]:
inv(0)

ZeroDivisionError: 0.0 cannot be raised to a negative power

In [57]:
def inverse(x):
    if x == 0:
        val = np.inf
    else:
        val = x**(-2)
    return val

In [58]:
inverse(0)

inf

## Exercises

1. Write down descriptions of what these methods do:

- `all()`
- `any()`
- `cumprod()`
- `cumsum()`
- `reshape()`
- `shape` --> No parentheses! This is an attribute and not a method.

2. Calculate the following using numpy:

- $\cos\left(\frac{\pi}{3}\right)$
- $\cosh\left(\frac{\pi}{3}\right)$

3. Write a function that will return the sum of the first $n$ terms of an array, where the user inputs both $n$ and the array.

4. Write a function that will return the logarithm of the standard deviation of an input array.

5. Use numpy to multiply the complex numbers $257 + 134i$ and $987 - 643i$.

6. **Euler's Formula.** How could we use numpy to test Euler's Formula: $e^{\pi i} + 1 = 0$?